### ISSUE TITLE
preproc.py: Error if no match for sentence end in find_sign_index

### ISSUE THREAD

**Issue by jbekesi** [Goli-SF/MLNA#1]
If there is no match for sentence end markers in `find_sign_index`, `None` is returned which throws an
error in `translate_long_text`:  something like `cannot concat int type and None` (for `cut_index`).

Unless it is important for the workflow somewhere else, I would suggest to return -1 or 0 for a missing match instead of `None`.

**Comment by Goli-SF** [comment]
Important tip, thanks @jbekesi! I'll get to it!

**Comment by Goli-SF** [comment]
Important tip, thanks @jbekesi! I updated the code and resolved the issue.
